### PR TITLE
Fix not handling OAuth errors

### LINKED ISSUE #1464: [Auth UI] Handle user quitting Facebook login flow
If user tries to connect Facebook, but clicks "Not Now" on Facebook login page, it will go to a page unable to load.

- Skygear Server Date/Version: Not sure
- Application Platform: Testing on client app

#### Expected Results
Should go back to connect account page.

#### Actual Results
It goes to a blank page.

#### Steps to reproduce
1. Connect Facebook
2. See Facebook login dialog, click "Not Now"
3. See it goes to a page unable to load

### PR DESCRIPTION
**Pull request by kiootic**
fix #1464

### CODE REVIEW

File: pkg/auth/dependency/webapp/authenticate_provider_impl.go [hunk 1]
```diff
@@ -607,6 +605,12 @@ func (p *AuthenticateProviderImpl) HandleSSOCallback(w http.ResponseWriter, r *h
 		})
 	}
 
+	oauthError := r.Form.Get("error")
+	if oauthError != "" {
+		err = sso.NewSSOFailed(sso.SSOUnauthorized, "login failed")
```
Comment (louischan-oursky) [inline pkg/auth/dependency/webapp/authenticate_provider_impl.go:610]: I remember in the spec there is `error` and `error_description`. Maybe we should forward them to enable better diagnosis?

Comment (kiootic) [reply pkg/auth/dependency/webapp/authenticate_provider_impl.go:610]: `error` is an error code, therefore should not be displayed. I'll include `error_description` in the error message instead.

Comment (louischan-oursky) [reply pkg/auth/dependency/webapp/authenticate_provider_impl.go]: I guess it is not harmful to show the error code as well.

Comment (kiootic) [reply pkg/auth/dependency/webapp/authenticate_provider_impl.go]: The UX can be confusing to end-user, since the error code often contains technical terms.

Comment (louischan-oursky) [reply pkg/auth/dependency/webapp/authenticate_provider_impl.go]: OK. Let's revisit this later. I was thinking about using `<script>` to log the error code to console......
