### PR TITLE
Unlink not found oauth identity

### LINKED ISSUE #1308: Unlink non-existent SSO provider gives HTTP 500
The error got printed to stderr is `"principal not found"` which is should considered expected error instead of unexpected error.

### PR DESCRIPTION
**Pull request by louischan-oursky**
fix #1308

### CODE REVIEW

File: pkg/auth/dependency/principal/oauth/error.go [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package oauth
+
+import (
+	"github.com/skygeario/skygear-server/pkg/core/skyerr"
+)
+
+var ErrIdentityNotFound = skyerr.NotFound.WithReason("OAuthIdentityNotFound").New("oauth identity not found")
```
Comment (kiootic) [inline pkg/auth/dependency/principal/oauth/error.go:7]: I think this error can be moved up to `principal` package, or even update the existing principal not found error, since there is no need for client to know the type of identity.

Comment (louischan-oursky) [reply pkg/auth/dependency/principal/oauth/error.go]: I updated the principal not found error to skyerr. However, we still have some error in `principal/password/error.go` that may overlap with those in `principal/error.go`

Comment (kiootic) [reply pkg/auth/dependency/principal/oauth/error.go]: Oh I forgot about the error in password package. If so, I think these skyerrs should belongs to the handler layer instead. So providers would return a simple error (`ErrNotFound`), and handlers would translate it into skyerrs for each group of APIs.

Comment (louischan-oursky) [reply pkg/auth/dependency/principal/oauth/error.go]: So revert to my original change?

Comment (kiootic) [reply pkg/auth/dependency/principal/oauth/error.go]: Yes, sorry for this. It would be better to also move the not found errors into the handler (i.e. into `loginid` and `sso` packages in handlers)

Comment (louischan-oursky) [reply pkg/auth/dependency/principal/oauth/error.go]: Updated.
