### PR TITLE
OAuth response mode

### LINKED ISSUE #1503: OAuth response mode
Client may use XHR to interact with Auth UI. Custom URL scheme redirect does not work with XHR. Therefore, we need an extra endpoint to use HTTP 302 redirect. That endpoint can also support `response_mode=form_post`.

### PR DESCRIPTION
**Pull request by louischan-oursky**
fix #1503

### CODE REVIEW

File: pkg/auth/dependency/oauth/handler/response_mode.go [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+window.location.href = "{{ .redirect_uri }}"
+</script>
+</body>
+</html>
+`
+
+const formPostTemplateString = `<!DOCTYPE html>
+<html>
+<head>
+<title>Submit this form</title>
```
Comment (kiootic) [inline pkg/auth/dependency/oauth/handler/response_mode.go:28]: For better UX, we can use localized app name?

Comment (louischan-oursky) [reply pkg/auth/dependency/oauth/handler/response_mode.go:28]: 90% people wont see this. When they see this, what they need to do is to submit this form. But localizing this string has some overhead.

Comment (kiootic) [reply pkg/auth/dependency/oauth/handler/response_mode.go:28]: I think at least this message should be moved to body (and may need localization in future), since users seldom pay attention to title.

Comment (louischan-oursky) [reply pkg/auth/dependency/oauth/handler/response_mode.go:28]: Move the message as `<noscript>` to `<body>`
